import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'


export default function Home() {
  // 노션용
  /* const [products, setProducts] = useState<{id:string; properties:{id:string}[]}[]>([]) */
  /* useEffect(() => {
    fetch('/api/get-items')
      .then(res => res.json())
      .then(data => setProducts(data.items))
  }, []); */

  const [products, setProducts] = useState<{id:string; name:string}[]>([])
  useEffect(() => {
    fetch('/api/get-products')
      .then(res => res.json())
      .then(data => setProducts(data.items))
  }, []);

  const inputRef = useRef<HTMLInputElement>(null)

  const HandleClick = () => {
    if(inputRef.current == null || inputRef.current.value ==''){
      alert('name을 넣어주세요')
      return
    }
    fetch(`/api/add-item?name=${inputRef.current.value}`)
      .then(res => res.json())
      .then(data => alert(data.message))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{padding:50}}>
        <br />
        <div className={styles.description}>
          <input type="text" ref={inputRef} placeholder='name' />
          <button onClick={HandleClick}>Add Jacket</button>
        </div>
        <br />
        <div>
          <p>Product list</p>
          {
            products && products.map((item) => (
              <div key={item.id}>{item.name}</div>
            ))
          }

          {/* 노션용
          {
            products &&
            products.map(item => (
              <div key={item.id}>
                {JSON.stringify(item)}
                {item.properties &&
                  Object.entries(item.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `/api/get-detail?pageId=${item.id}&propertyId=${value.id}`
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)))
                      }}
                    >
                      {key}
                    </button>
                ))}
                <br />
                <br />
              </div>
            ))
          } */}
        </div>
      </div>
    </>
  )
}
